### PR TITLE
Update session filter for congressional district lookup

### PR DESCRIPTION
**Pull request by kokonakajima**
Addresses an issue where we weren't getting the most recent district result for PA address lookups.

### CODE REVIEW

**Review by hanbyul-here — APPROVED** [review]
you didn't ask but I am still giving you an approval

**Comment by kokonakajima** [comment]
👻sneaking in a question for @dphiffer 👻 

do you happen to remember the reasoning behind updating the session filter for the congressional district lookup? we ran into an issue like the one you mentioned in your comment, where recently redistricted districts weren't captured. (which resulted in incorrect congressional districts for the pip lookup in PA)

wasn't sure if the updated filter was a measure against some bugs that we aren't foreseeing now, though.

no need to respond to this if you don't want 😎

**Comment by dphiffer** [comment]
Oh man, I can't remember what this is about but at first glance it sure looks like an off-by-one error. I think there was also some redistricting in ... NC? VA? I forget, but it might be worth testing those ones out.

**Comment by dphiffer** [comment]
Also hi hello, I miss you all!

**Comment by kokonakajima** [comment]
ahh hello! miss you too!!!! and that's super helpful info, thanks, will look into the NC/VA redistricting as well.

**Pull request merged**
