### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by alisonag**
To do:
- [x] lock all packages in requirements.txt to a version
- [x] finish running through all make scripts to see if any dependencies are missing

This is ready for review. [Here are instructions](https://github.com/aclu-national/elections-api/blob/01620d399b51261e4677de38f3b1dbe2ce5c4386/docs/docker.md) for running the container.

~As I was setting this up, I realized that the photo paths have moved, so you may want to skip `congress_photos` in the `sources/Makefile` until we are able to update these paths.~

If you've never run the source scripts, you'll need to run `make` from the following places:
- `/sources` ~(but comment out `congress_photos` from the sources makefile temporarily)~
- `/data`
- `/elections-api-private`
- root of repo`/`

### CODE REVIEW

**Comment by hanbyul-here** [comment]
I have some suggestions for documentation  for how to run docker (I am on 2.2.0.5, and had to edit the paths that Docker has access to.+ also google and mapbox token are required.), but this works 🥳 yayayay!

**Review by hanbyul-here — APPROVED** [review]

**Review by kokonakajima — APPROVED** [review]
Amazing!!!! this looks great 😱I checked out the v2 endpoints and they look like what i had running locally pre-Docker.

Notes from running through the setup:

- like Hanbyul mentioned, i also had to edit the paths that Docker had access to. (did this in Docker Desktop through Preferences > Resources > File sharing)
- i think the `pip` endpoints require `make election_races && make election_candidates && make targeted` in addition to `make all` from the root level. `make election_races` gave me a psql error because of the line `psql elections < sources/aclu/aclu_election_races.sql` in the Makefile:
```
psql elections < sources/aclu/aclu_election_races.sql
	psql: could not connect to server: No such file or directory
		Is the server running locally and accepting
		connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

**Comment by alisonag** [comment]
Thanks for reviewing! I updated the make `election_races` command so that it should work inside or outside docker.

I also updated the [doc](https://github.com/aclu-national/elections-api/blob/2513ed568b4873fcbc03c607b3d4de1ca9734a69/docs/docker.md) with some more info about docker preferences and a few other things.

I also noticed that `/v2/geoip` won't automatically detect your IP address. We need to set up `x-forwarded-for`, which is it a little bit out of my wheelhouse here (maybe setting up nginx would help, but it would take me a while to figure it out). There's a workaround where you can still test the endpoint locally by adding your IP as a query param (`/v2/geoip?ip=xx.xxx.xxx.xx`), so I think we can leave things as is for now and address later.

**Comment by kokonakajima** [comment]
Cool, i ran `make election_races` inside/outside the container and it worked!

For what it's worth the `geoip` endpoint also didn't automatically detect an IP when I ran the server locally (without docker). You might have seen this already but on the aws machines it probably has to do with https://github.com/aclu-national/elections-api/blob/a157c088118c76396211561ef781e55d04934750/server/nginx.conf#L22

**Pull request merged**
